version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: reminders_plus_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: remindersPlus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AndrejSQL
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    container_name: reminders_plus_backend
    build: ./backend
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/remindersPlus
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=AndrejSQL
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  frontend:
    container_name: reminders_plus_frontend
    build: ./frontend
    restart: on-failure
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres-data: