apiVersion: v1
kind: ConfigMap
metadata:
  name: reminders-config
  namespace: default
data:
  DB_HOST: "reminders-db-service"
  DB_PORT: "5432"
  DB_NAME: "remindersPlus"
---
apiVersion: v1
kind: Secret
metadata:
  name: reminders-secrets
  namespace: default
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: QW5kcmVqU1FM