apiVersion: apps/v1
kind: Deployment
metadata:
  name: reminders-db
  namespace: default
  labels:
    app: reminders-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reminders-db
  template:
    metadata:
      labels:
        app: reminders-db
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: reminders-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: reminders-secrets
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reminders-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: reminders-db
  namespace: default
spec:
  selector:
    app: reminders-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP